import streamlit as st 

st.set_page_config(
    page_title="Spam or Ham Features",
    page_icon="🎮🕹)",
)

st.title("SpamGuard Pro")

#st.write("SpamGuard Pro is an innovative spam detection system meticulously crafted from scratch, utilizing the powerful combination of Natural Language Processing (NLP) and advanced machine learning techniques. This comprehensive solution goes beyond conventional spam filters, offering users a robust defense mechanism against unwanted and potentially harmful messages across various communication channels. Whether it's emails inundated with phishing attempts, suspicious SMS messages, or misleading news articles, SpamGuard Pro employs state-of-the-art algorithms to predict with remarkable accuracy whether the content is spam or not. Through continuous learning and adaptation, the system ensures a higher level of precision, providing users with a shield against the ever-evolving landscape of spam threats in the digital realm.With a focus on user empowerment, SpamGuard Pro seamlessly integrates into everyday communication platforms, offering a unified defense against spam across email, SMS, and news feeds. Leveraging NLP allows the system to understand the nuanced patterns and contextual cues in human language, enabling it to discern between legitimate and malicious content effectively. The machine learning algorithms, trained on diverse datasets, enable SpamGuard Pro to evolve and adapt to emerging spam techniques, staying one step ahead of potential threats. As a result, users can experience a safer and more secure digital communication environment, where the sophisticated spam detection capabilities of SpamGuard Pro enhance the overall quality of their online interactions.")

st.write("With a focus on user empowerment, SpamGuard Pro seamlessly integrates into everyday communication platforms, offering a unified defense against spam across email, SMS, and news feeds. Leveraging NLP allows the system to understand the nuanced patterns and contextual cues in human language, enabling it to discern between legitimate and malicious content effectively. The machine learning algorithms, trained on diverse datasets, enable SpamGuard Pro to evolve and adapt to emerging spam techniques, staying one step ahead of potential threats. As a result, users can experience a safer and more secure digital communication environment, where the sophisticated spam detection capabilities of SpamGuard Pro enhance the overall quality of their online interactions")